// Code generated by go-enum
// DO NOT EDIT!

package api

import (
	"fmt"
)

const (
	// SeverityInfo is a Severity of type Info
	SeverityInfo Severity = iota
	// SeverityWarning is a Severity of type Warning
	SeverityWarning
	// SeverityError is a Severity of type Error
	SeverityError
)

const _SeverityName = "InfoWarningError"

var _SeverityMap = map[Severity]string{
	0: _SeverityName[0:4],
	1: _SeverityName[4:11],
	2: _SeverityName[11:16],
}

func (i Severity) String() string {
	if str, ok := _SeverityMap[i]; ok {
		return str
	}
	return fmt.Sprintf("Severity(%d)", i)
}

var _SeverityValue = map[string]Severity{
	_SeverityName[0:4]:   0,
	_SeverityName[4:11]:  1,
	_SeverityName[11:16]: 2,
}

// ParseSeverity attempts to convert a string to a Severity
func ParseSeverity(name string) (Severity, error) {
	if x, ok := _SeverityValue[name]; ok {
		return Severity(x), nil
	}
	return Severity(0), fmt.Errorf("%s is not a valid Severity", name)
}
